### PR TITLE
Support for x86_64

### PR DESCRIPTION
**Pull request by paulo-raca**
The code follows the same structure of x86, but it doesn't work. Any ideas?

This is a follow-up for #69

### CODE REVIEW

**Comment by rk700** [comment]
As for x86_64, the first 6 arguments are passed in registers RDI, RSI, RDX, RCX, R8, R9. So I think `rdi` should be used instead of `rax`.

**Comment by rk700** [comment]
http://androidxref.com/7.0.0_r1/xref/art/runtime/arch/x86_64/quick_entrypoints_x86_64.S#455:

```
    /*
     * Quick invocation stub.
     * On entry:
     *   [sp] = return address
     *   rdi = method pointer
     *   rsi = argument array that must at least contain the this pointer.
     *   rdx = size of argument array in bytes
     *   rcx = (managed) thread pointer
     *   r8 = JValue* result
     *   r9 = char* shorty
     */
```

**Comment by paulo-raca** [comment]
That worked!
Thanks, I wouldn't have figured that out.

**Comment by paulo-raca** [comment]
A quick update on the tests:

x86_64 doesn't work on API versions 21, 22, 23 and 27.
x86 doesn't work on API 27.

I'm guessing 21-23 might be caused by #61
Any ideas about the issue on Android 27? Does it affect ARM device too? (I don't have any ARM device with 7.1 here)

**Comment by rk700** [comment]
It's weird on API 27 since my previous demo works but the unit test fails. The debugger shows it crashes when updating the cached method. Needs to take a deeper look at it.

**Comment by rk700** [comment]
I think maybe we could create a new issue to track the problem.

**Pull request merged**
